//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Routing
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Statistics", Namespace="http://schemas.datacontract.org/2004/07/Routing.Stats")]
    public partial class Statistics : object
    {
        
        private Routing.Statistics.StationsStatistics[] stationsStatsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Routing.Statistics.StationsStatistics[] stationsStats
        {
            get
            {
                return this.stationsStatsField;
            }
            set
            {
                this.stationsStatsField = value;
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Statistics.StationsStatistics", Namespace="http://schemas.datacontract.org/2004/07/Routing.Stats")]
        public partial class StationsStatistics : object
        {
            
            private int occurencek__BackingFieldField;
            
            private Routing.Station stationk__BackingFieldField;
            
            private Routing.Statistics.Type typek__BackingFieldField;
            
            [System.Runtime.Serialization.DataMemberAttribute(Name="<occurence>k__BackingField", IsRequired=true)]
            public int occurencek__BackingField
            {
                get
                {
                    return this.occurencek__BackingFieldField;
                }
                set
                {
                    this.occurencek__BackingFieldField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(Name="<station>k__BackingField", IsRequired=true)]
            public Routing.Station stationk__BackingField
            {
                get
                {
                    return this.stationk__BackingFieldField;
                }
                set
                {
                    this.stationk__BackingFieldField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(Name="<type>k__BackingField", IsRequired=true)]
            public Routing.Statistics.Type typek__BackingField
            {
                get
                {
                    return this.typek__BackingFieldField;
                }
                set
                {
                    this.typek__BackingFieldField = value;
                }
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Statistics.Type", Namespace="http://schemas.datacontract.org/2004/07/Routing.Stats")]
        public enum Type : int
        {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            DEFAULT = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            DEPARTURE = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ARRIVAL = 2,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Station", Namespace="http://schemas.datacontract.org/2004/07/WebProxyService.JSONClasses")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Routing.GeoGeoJson[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Routing.GeoGeoJson))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Routing.GeoFeature[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Routing.GeoFeature))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Routing.GeoGeometry))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Routing.GeoProperties))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Routing.GeoSegment[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Routing.GeoSegment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Routing.GeoStep[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Routing.GeoStep))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Routing.GeoSummary))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Routing.GeoMetadata))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Routing.GeoEngine))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Routing.GeoQuery))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Routing.Statistics))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Routing.Statistics.StationsStatistics[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Routing.Statistics.StationsStatistics))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Routing.Statistics.Type))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(double[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(double[][]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(int[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Routing.MainStands))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Routing.Availabilities))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Routing.OverflowStands))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Routing.Position))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Routing.TotalStands))]
    public partial class Station : object
    {
        
        private string addressField;
        
        private bool bankingField;
        
        private bool bonusField;
        
        private bool connectedField;
        
        private string contractNameField;
        
        private System.Nullable<System.DateTime> lastUpdateField;
        
        private Routing.MainStands mainStandsField;
        
        private string nameField;
        
        private int numberField;
        
        private bool overflowField;
        
        private Routing.OverflowStands overflowStandsField;
        
        private Routing.Position positionField;
        
        private object shapeField;
        
        private string statusField;
        
        private Routing.TotalStands totalStandsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool banking
        {
            get
            {
                return this.bankingField;
            }
            set
            {
                this.bankingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bonus
        {
            get
            {
                return this.bonusField;
            }
            set
            {
                this.bonusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool connected
        {
            get
            {
                return this.connectedField;
            }
            set
            {
                this.connectedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contractName
        {
            get
            {
                return this.contractNameField;
            }
            set
            {
                this.contractNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> lastUpdate
        {
            get
            {
                return this.lastUpdateField;
            }
            set
            {
                this.lastUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Routing.MainStands mainStands
        {
            get
            {
                return this.mainStandsField;
            }
            set
            {
                this.mainStandsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool overflow
        {
            get
            {
                return this.overflowField;
            }
            set
            {
                this.overflowField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Routing.OverflowStands overflowStands
        {
            get
            {
                return this.overflowStandsField;
            }
            set
            {
                this.overflowStandsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Routing.Position position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object shape
        {
            get
            {
                return this.shapeField;
            }
            set
            {
                this.shapeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Routing.TotalStands totalStands
        {
            get
            {
                return this.totalStandsField;
            }
            set
            {
                this.totalStandsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MainStands", Namespace="http://schemas.datacontract.org/2004/07/WebProxyService.JSONClasses")]
    public partial class MainStands : object
    {
        
        private Routing.Availabilities availabilitiesField;
        
        private int capacityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Routing.Availabilities availabilities
        {
            get
            {
                return this.availabilitiesField;
            }
            set
            {
                this.availabilitiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int capacity
        {
            get
            {
                return this.capacityField;
            }
            set
            {
                this.capacityField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OverflowStands", Namespace="http://schemas.datacontract.org/2004/07/WebProxyService.JSONClasses")]
    public partial class OverflowStands : object
    {
        
        private Routing.Availabilities availabilitiesField;
        
        private int capacityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Routing.Availabilities availabilities
        {
            get
            {
                return this.availabilitiesField;
            }
            set
            {
                this.availabilitiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int capacity
        {
            get
            {
                return this.capacityField;
            }
            set
            {
                this.capacityField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Position", Namespace="http://schemas.datacontract.org/2004/07/WebProxyService.JSONClasses")]
    public partial class Position : object
    {
        
        private double latitudeField;
        
        private double longitudeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TotalStands", Namespace="http://schemas.datacontract.org/2004/07/WebProxyService.JSONClasses")]
    public partial class TotalStands : object
    {
        
        private Routing.Availabilities availabilitiesField;
        
        private int capacityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Routing.Availabilities availabilities
        {
            get
            {
                return this.availabilitiesField;
            }
            set
            {
                this.availabilitiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int capacity
        {
            get
            {
                return this.capacityField;
            }
            set
            {
                this.capacityField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Geo.GeoJson", Namespace="http://schemas.datacontract.org/2004/07/Routing.JSONClasses")]
    public partial class GeoGeoJson : object
    {
        
        private double[] bboxField;
        
        private Routing.GeoFeature[] featuresField;
        
        private Routing.GeoMetadata metadataField;
        
        private Routing.Station stationField;
        
        private string typeField;
        
        private double[][] waypointsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] bbox
        {
            get
            {
                return this.bboxField;
            }
            set
            {
                this.bboxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Routing.GeoFeature[] features
        {
            get
            {
                return this.featuresField;
            }
            set
            {
                this.featuresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Routing.GeoMetadata metadata
        {
            get
            {
                return this.metadataField;
            }
            set
            {
                this.metadataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Routing.Station station
        {
            get
            {
                return this.stationField;
            }
            set
            {
                this.stationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[][] waypoints
        {
            get
            {
                return this.waypointsField;
            }
            set
            {
                this.waypointsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Geo.Feature", Namespace="http://schemas.datacontract.org/2004/07/Routing.JSONClasses")]
    public partial class GeoFeature : object
    {
        
        private double[] bboxField;
        
        private Routing.GeoGeometry geometryField;
        
        private Routing.GeoProperties propertiesField;
        
        private string typeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] bbox
        {
            get
            {
                return this.bboxField;
            }
            set
            {
                this.bboxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Routing.GeoGeometry geometry
        {
            get
            {
                return this.geometryField;
            }
            set
            {
                this.geometryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Routing.GeoProperties properties
        {
            get
            {
                return this.propertiesField;
            }
            set
            {
                this.propertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Geo.Geometry", Namespace="http://schemas.datacontract.org/2004/07/Routing.JSONClasses")]
    public partial class GeoGeometry : object
    {
        
        private double[][] coordinatesField;
        
        private string typeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[][] coordinates
        {
            get
            {
                return this.coordinatesField;
            }
            set
            {
                this.coordinatesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Geo.Properties", Namespace="http://schemas.datacontract.org/2004/07/Routing.JSONClasses")]
    public partial class GeoProperties : object
    {
        
        private Routing.GeoSegment[] segmentsField;
        
        private Routing.GeoSummary summaryField;
        
        private int[] way_pointsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Routing.GeoSegment[] segments
        {
            get
            {
                return this.segmentsField;
            }
            set
            {
                this.segmentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Routing.GeoSummary summary
        {
            get
            {
                return this.summaryField;
            }
            set
            {
                this.summaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] way_points
        {
            get
            {
                return this.way_pointsField;
            }
            set
            {
                this.way_pointsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Geo.Segment", Namespace="http://schemas.datacontract.org/2004/07/Routing.JSONClasses")]
    public partial class GeoSegment : object
    {
        
        private double distanceField;
        
        private double durationField;
        
        private Routing.GeoStep[] stepsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double distance
        {
            get
            {
                return this.distanceField;
            }
            set
            {
                this.distanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Routing.GeoStep[] steps
        {
            get
            {
                return this.stepsField;
            }
            set
            {
                this.stepsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Geo.Step", Namespace="http://schemas.datacontract.org/2004/07/Routing.JSONClasses")]
    public partial class GeoStep : object
    {
        
        private double distanceField;
        
        private double durationField;
        
        private string instructionField;
        
        private string nameField;
        
        private int typeField;
        
        private int[] way_pointsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double distance
        {
            get
            {
                return this.distanceField;
            }
            set
            {
                this.distanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string instruction
        {
            get
            {
                return this.instructionField;
            }
            set
            {
                this.instructionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] way_points
        {
            get
            {
                return this.way_pointsField;
            }
            set
            {
                this.way_pointsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Geo.Summary", Namespace="http://schemas.datacontract.org/2004/07/Routing.JSONClasses")]
    public partial class GeoSummary : object
    {
        
        private double distanceField;
        
        private double durationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double distance
        {
            get
            {
                return this.distanceField;
            }
            set
            {
                this.distanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Geo.Metadata", Namespace="http://schemas.datacontract.org/2004/07/Routing.JSONClasses")]
    public partial class GeoMetadata : object
    {
        
        private string attributionField;
        
        private Routing.GeoEngine engineField;
        
        private Routing.GeoQuery queryField;
        
        private string serviceField;
        
        private long timestampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string attribution
        {
            get
            {
                return this.attributionField;
            }
            set
            {
                this.attributionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Routing.GeoEngine engine
        {
            get
            {
                return this.engineField;
            }
            set
            {
                this.engineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Routing.GeoQuery query
        {
            get
            {
                return this.queryField;
            }
            set
            {
                this.queryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string service
        {
            get
            {
                return this.serviceField;
            }
            set
            {
                this.serviceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Geo.Engine", Namespace="http://schemas.datacontract.org/2004/07/Routing.JSONClasses")]
    public partial class GeoEngine : object
    {
        
        private System.DateTime build_dateField;
        
        private System.DateTime graph_dateField;
        
        private string versionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime build_date
        {
            get
            {
                return this.build_dateField;
            }
            set
            {
                this.build_dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime graph_date
        {
            get
            {
                return this.graph_dateField;
            }
            set
            {
                this.graph_dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Geo.Query", Namespace="http://schemas.datacontract.org/2004/07/Routing.JSONClasses")]
    public partial class GeoQuery : object
    {
        
        private double[][] coordinatesField;
        
        private string formatField;
        
        private string profileField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[][] coordinates
        {
            get
            {
                return this.coordinatesField;
            }
            set
            {
                this.coordinatesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string format
        {
            get
            {
                return this.formatField;
            }
            set
            {
                this.formatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string profile
        {
            get
            {
                return this.profileField;
            }
            set
            {
                this.profileField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Availabilities", Namespace="http://schemas.datacontract.org/2004/07/WebProxyService.JSONClasses")]
    public partial class Availabilities : object
    {
        
        private int bikesField;
        
        private int electricalBikesField;
        
        private int electricalInternalBatteryBikesField;
        
        private int electricalRemovableBatteryBikesField;
        
        private int mechanicalBikesField;
        
        private int standsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int bikes
        {
            get
            {
                return this.bikesField;
            }
            set
            {
                this.bikesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int electricalBikes
        {
            get
            {
                return this.electricalBikesField;
            }
            set
            {
                this.electricalBikesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int electricalInternalBatteryBikes
        {
            get
            {
                return this.electricalInternalBatteryBikesField;
            }
            set
            {
                this.electricalInternalBatteryBikesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int electricalRemovableBatteryBikes
        {
            get
            {
                return this.electricalRemovableBatteryBikesField;
            }
            set
            {
                this.electricalRemovableBatteryBikesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int mechanicalBikes
        {
            get
            {
                return this.mechanicalBikesField;
            }
            set
            {
                this.mechanicalBikesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int stands
        {
            get
            {
                return this.standsField;
            }
            set
            {
                this.standsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Routing.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStatistics", ReplyAction="http://tempuri.org/IService1/GetStatisticsResponse")]
        System.Threading.Tasks.Task<Routing.Statistics> GetStatisticsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Save", ReplyAction="http://tempuri.org/IService1/SaveResponse")]
        System.Threading.Tasks.Task<bool> SaveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGeoData", ReplyAction="http://tempuri.org/IService1/GetGeoDataResponse")]
        System.Threading.Tasks.Task<Routing.GeoGeoJson[]> GetGeoDataAsync(string departure, string arrival);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IService1Channel : Routing.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Routing.IService1>, Routing.IService1
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Routing.Statistics> GetStatisticsAsync()
        {
            return base.Channel.GetStatisticsAsync();
        }
        
        public System.Threading.Tasks.Task<bool> SaveAsync()
        {
            return base.Channel.SaveAsync();
        }
        
        public System.Threading.Tasks.Task<Routing.GeoGeoJson[]> GetGeoDataAsync(string departure, string arrival)
        {
            return base.Channel.GetGeoDataAsync(departure, arrival);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/Routing/Service1/soap");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
